[package]
name = "roguelike"
version = "0.1.0"
authors = ["okeeffet"]
edition = "2018"

[dependencies]
tcod = "*"
rand_core = "*"
rand_isaac = "*"
rand = "*"
pathfinding = "*"
hashbrown = "*"
dirs = "*"